### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by Peanutt47** [thanidacwn/veggie-hub#90]
![image](https://github.com/Nantawat6510545543/KU-ACTIVE/assets/85238329/d7e4321f-706c-4e76-86e3-90588330be16)
When i edit filter manual return Server Error (500)

**Comment by thanidacwn** [comment]
You found server 500 because the website had too many visitors last night. causing the connection to exceed Our server can handle it. As of now, the problem has been fixed. and return to normal use. Thank you
