### ISSUE TITLE
When clicking on the link, there is a chance of getting a Server Error (500).

### ISSUE THREAD

**Issue by Nantawat6510545543** [thanidacwn/veggie-hub#92]
![image](https://github.com/thanidacwn/veggie-hub/assets/114897362/45105cec-8c65-4244-9495-4d261d03bde1)
![image](https://github.com/thanidacwn/veggie-hub/assets/114897362/7946c45d-ddcb-4a62-b647-9a8ac946c488)
![image](https://github.com/thanidacwn/veggie-hub/assets/114897362/f6fa1fa2-0d02-473a-b432-a772092f07ce)

**Comment by thanidacwn** [comment]
Sorry for found server 500 because the website had too many visitors last night. causing the connection to exceed Our server can handle it. As of now, the problem has been fixed. and return to normal use. Thank you
