### ISSUE TITLE
Skip the coninue page before go to choose email.

### ISSUE THREAD

**Issue by Sankrub** [thanidacwn/veggie-hub#95]
Maybe you can skip this page? Or if you don't want then fine not a big problem.
<img width="1278" alt="Screenshot 2566-11-24 at 17 03 46" src="https://github.com/thanidacwn/veggie-hub/assets/92860717/f3065f9a-4425-42b3-a028-b9796a2462a6">

**Comment by PanupunJanin** [comment]
It's not a defect for this application

**Comment by PanupunJanin** [comment]
It is for the user to use the simple menu, but will consider the skip to be implemented if the time is not a problem.
