### ISSUE TITLE
Can't login with another account 

### ISSUE THREAD

**Issue by 21Gxme** [thanidacwn/veggie-hub#96]
tried logging in with a different account. But it can't be done. because another account that logged in before that becomes the last logged in account
<img width="1470" alt="image" src="https://github.com/thanidacwn/veggie-hub/assets/113856957/3bd4c88d-6634-44b3-9679-3a1a8aaf3b02">

**Comment by PanupunJanin** [comment]
Need more information of how to replicate this

**Comment by 21Gxme** [comment]
Uploading Screen Recording 2566-11-26 at 03.07.25.mov…

**Comment by 21Gxme** [comment]
https://github.com/thanidacwn/veggie-hub/assets/113856957/d04f359f-b8c9-4465-a1ee-005046ab0a56
