### ISSUE TITLE
I have the same restaurant in my bookmarks

### ISSUE THREAD

**Issue by 21Gxme** [thanidacwn/veggie-hub#97]
<img width="1469" alt="image" src="https://github.com/thanidacwn/veggie-hub/assets/113856957/fbd46c47-882c-4492-a52a-6bb60b566191">
I think if it's the same it should just be one.

**Comment by PanupunJanin** [comment]
Need more information of how to replicate this

**Comment by thanidacwn** [comment]
fixed
